### PR TITLE
Return promises

### PR DESCRIPTION
**Pull request by jessehansen**
It's also a complete refactor. I have deprecated calling the constructors with `new`, renamed AbstractClient to RoutedClient, and deprecated this version of "success" (pointed to svcutils).

### CODE REVIEW

**Comment by rizowski** [comment]
One of the things that I have been doing to tools if we are still using assert is changing it to joi since I think joi gives better descriptions as to what is wrong with your arguments. Trusted endpoint got a little hairy but it definitely helped debugging what might have been wrong with it.

**Comment by jessehansen** [comment]
This also (I believe) addresses #7

**Comment by jessehansen** [comment]
I'm going to switch to Joi in a different PR.

**Comment by rizowski** [comment]
👍  LGTM least from what I can tell.

**Comment by ghost** [comment]
I like the refactor. I noticed you kept the metrics - I'm happy to see that as well even though we don't collect them or do anything with them yet.

**Pull request merged**
