### PR TITLE
ignore/warn json on read-only requests

### PR DESCRIPTION
**Pull request by jconley**
see https://github.com/LeisureLink/integration-hub-client/pull/60

### CODE REVIEW

**Comment by ghost** [comment]
This is a peculiar modification. Isn't it the caller's responsibility to perform a GET or a DELETE request without attaching a body [nor .json]? Seems if this is causing a problem then the technical debt lives elsewhere. By magically auto-correcting the call, the caller never gets a bloody nose so they'll just keep doing same thing.

**Comment by jconley** [comment]
@flitbit as much as i would like to throw an error punch to the nose... i dont want to break anything already deployed. (dont trust that we get enough testing these days).  and given gc lb's throw 400's b/c the http is non-compliant and doesn't give you enough info as to why - i figure we need to fix the issue to avoid wasting time on duplicitous debugging... and at least log/warn the user.

**Comment by jconley** [comment]
@flitbit also my best guess on why json: true was used in the first place, is that the underlying request npm doesn't parse json unless it's passed.  however it also says it serializes the value; unless they're lib is also smart and doesn't set the body on read-only requests...   maybe someone followed those patterns from long ago and it's been copied/pasted all this time.

**Comment by jessehansen** [comment]
How about not setting those things if `options.json === true`?

**Comment by jessehansen** [comment]
I agree with Phillip, detecting the method and saving the caller from theirself (themself?) doesn't make much sense. The real problem is that `json:true` is shorthand for setting `Accept: application/json` and trusted-client currently makes it also send the headers `Content-Length` and `Content-Type`, along with "true" as the request body. We should stop misinterpreting the argument instead. I implemented it that way in #8

**Comment by jconley** [comment]
@twindagger ideally yes, but if i decided to have it throw an error, then we'd risk the next build of any project blowing up in production (without changing the major version + good testing; which technically this would be a contract behavior change IMO) - in the current version, i dont trust that we have full integration tests that would expose a thrown error.

the point of logically avoiding it here in v1, is to prevent others from bumping into the obscure gc error and wasting time debugging it again.

also trusted-client does not use options.json to set the Accept; it always sets that by default. (as well as parsing json responses by default)

ideally i'd like to throw an error; but i'd rather not risk breaking production, or semver.  at least with a warning we can cull the logs for non-compliant projects.  of course that's optional.

although i heard we're not breaking production enough... let me know your preference(s).

**Comment by jconley** [comment]
@twindagger jesse, i changed this to match the json!==true logic that you have in your #8 PR... which i assume will be 2.x.  kosher?

**Comment by jessehansen** [comment]
@jconley - I think changing it to detect `true` and not send content in that case will prevent production blow-ups. I knew that trusted-client sets the Accept header by default - I was referring to request's behavior.

**Comment by jessehansen** [comment]
Looks good - I'll release this as 1.0.2 before releasing v2

**Pull request merged**
